### PR TITLE
Revised the filter ID description

### PR DESCRIPTION
**Pull request by brtnfld**
Revised  PR #158 regarding the filter ID description to align with the specifications outlined in the HDF5 documentation.

### CODE REVIEW

**Comment by brtnfld** [comment]
@markcmiller86, I revised the paragraph.

**Comment by markcmiller86** [comment]
> @markcmiller86, I revised the paragraph of PR #158

Is it true that 0...256 are also "reservable" by a 3rd party? Or, do you just want to avoid talking about that part of it in this doc? Only reason I ask is there is header file content suggesting that. Maybe the original doc was fine then.

**Comment by brtnfld** [comment]
> > @markcmiller86, I revised the paragraph of PR #158
> 
> Is it true that 0...256 are also "reservable" by a 3rd party? Or, do you just want to avoid talking about that part of it in this doc? Only reason I ask is there is header file content suggesting that. Maybe the original doc was fine then.

You are correct, H5Zpublic. It is okay to be more detailed as I can not find this information by searching our HDF5 documentation. If so, I'll remove the reference to VOLs and update the PR.

```
/**
 * \brief Filter identifiers
 *
 * \details Values 0 through 255 are for filters defined by the HDF5 library.
 *          Values 256 through 511 are available for testing new filters.
 *          Subsequent values should be obtained from the HDF5 development team
 *          at mailto:help@hdfgroup.org. These values will never change because
 *          they appear in the HDF5 files.
 */
```

**Comment by brtnfld** [comment]
I will work out some issues in the HDF5 documentation on this topic and then get back to this.

**Review by byrnHDF — APPROVED** [review]

**Review by lrknox — APPROVED** [review]

**Pull request merged**
