### PR TITLE
Update compression libs versions

### PR DESCRIPTION
**Pull request by byrnHDF**

### CODE REVIEW

**Review by brtnfld — CHANGES_REQUESTED** [review]
Regarding updating versions, I would rather see an action, for example, https://github.com/marketplace/actions/dependencies-autoupdate, that automatically detects version updates in these packages and would do a PR to update them.

**Comment by byrnHDF** [comment]
> Regarding updating versions, I would rather see an action, for example, https://github.com/marketplace/actions/dependencies-autoupdate, that automatically detects version updates in these packages and would do a PR to update them.

While having a check for updates is doable, the auto changes to code is not.

**Comment by byrnHDF** [comment]
We could add a workflow that reports the latest version available, but to compare that to values inside a file would need a bit of work. We do not have a "this is the versions of the compression libs we use" type of document.
We would have to parse either the cacheinit.cmake file or the CMakePresets.file for that info.

**Review by brtnfld — APPROVED** [review]
It looks okay if we minimize the manual steps involved in the future.

**Comment by byrnHDF** [comment]
Added create a json artifact for the compression libs involved (except bzip2 as they do not create any releases)

**Pull request merged**
